Disabled .bazelrc cache because it is probably causing
F:\anki2>\bazel\bazel  --output_user_root=\bazel\anki run --explain=bazel-.log --subcommands --show_progress --worker_verbose --verbose_failures --verbose_explanations=true --test_output=streamed  //qt:runanki -k --
INFO: Invocation ID: e1250061-cc1c-49b5-84e7-67eef424a10e
INFO: Repository local_config_sh instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:348:13: in <toplevel>
  F:/bazel/anki/rybdqld5/external/bazel_tools/tools/sh/sh_configure.bzl:83:14: in sh_configure
Repository rule sh_config defined at:
  F:/bazel/anki/rybdqld5/external/bazel_tools/tools/sh/sh_configure.bzl:72:28: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_sh':
   Traceback (most recent call last):
        File "F:/bazel/anki/rybdqld5/external/bazel_tools/tools/sh/sh_configure.bzl", line 56, column 24, in _sh_config_impl
                repository_ctx.file("BUILD", """
Error in file: java.nio.file.AccessDeniedException: F:\bazel\anki\rybdqld5\external\local_config_sh
ERROR: Error fetching repository: Traceback (most recent call last):
        File "F:/bazel/anki/rybdqld5/external/bazel_tools/tools/sh/sh_configure.bzl", line 56, column 24, in _sh_config_impl
                repository_ctx.file("BUILD", """
Error in file: java.nio.file.AccessDeniedException: F:\bazel\anki\rybdqld5\external\local_config_sh
WARNING: errors encountered while analyzing target '//qt:runanki': it will not be built
INFO: Analyzed target //qt:runanki (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Writing explanation of rebuilds to 'bazel-.log'
ERROR: command succeeded, but not all targets were analyzed
INFO: Build completed, shutting down worker pool...
INFO: Elapsed time: 2.411s, Critical Path: 0.22s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

F:\anki2>run